version: '2'
services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:0.10.1.1
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      KAFKA_ADVERTISED_HOST_NAME: [INSERT IP ADDRESS HERE]
#      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
